services:
  valkey-node-primary-0:
    image: bitnamilegacy/valkey-cluster:7.2.5-debian-12-r4
    networks:
      cluster_subnet:
        ipv4_address: 172.16.1.10
    environment: &environment_primary
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'VALKEY_NODES=valkey-node-primary-0 valkey-node-primary-1 valkey-node-primary-2'
    healthcheck: &healthcheck_primary
      test: [ "CMD-SHELL", "OUT=`valkey-cli cluster slots`; echo $$OUT | grep 172.16.1.10 || exit 1; echo $$OUT | grep 172.16.1.11 || exit 1; echo $$OUT | grep 172.16.1.12 || exit 1; echo $$OUT | grep 172.16.1.13 || exit 1; echo $$OUT | grep 172.16.1.14 || exit 1; echo $$OUT | grep 172.16.1.15 || exit 1;" ]
      interval: 1s
      timeout: 3s
      retries: 30

  valkey-node-primary-1:
    image: bitnamilegacy/valkey-cluster:7.2.5-debian-12-r4
    networks:
      cluster_subnet:
        ipv4_address: 172.16.1.11
    environment: *environment_primary
    healthcheck: *healthcheck_primary

  valkey-node-primary-2:
    image: bitnamilegacy/valkey-cluster:7.2.5-debian-12-r4
    networks:
      cluster_subnet:
        ipv4_address: 172.16.1.12
    environment: *environment_primary
    healthcheck: *healthcheck_primary

  valkey-node-primary-3:
    image: bitnamilegacy/valkey-cluster:7.2.5-debian-12-r4
    networks:
      cluster_subnet:
        ipv4_address: 172.16.1.13
    environment: *environment_primary
    healthcheck: *healthcheck_primary

  valkey-node-primary-4:
    image: bitnamilegacy/valkey-cluster:7.2.5-debian-12-r4
    networks:
      cluster_subnet:
        ipv4_address: 172.16.1.14
    environment: *environment_primary
    healthcheck: *healthcheck_primary

  valkey-node-primary-5:
    image: bitnamilegacy/valkey-cluster:7.2.5-debian-12-r4
    networks:
      cluster_subnet:
        ipv4_address: 172.16.1.15
    environment: *environment_primary
    healthcheck: *healthcheck_primary

  valkey-node-backup-0:
    image: bitnamilegacy/valkey-cluster:7.2.5-debian-12-r4
    networks:
      cluster_subnet:
        ipv4_address: 172.16.1.20
    environment: &environment_backup
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'VALKEY_NODES=valkey-node-backup-0 valkey-node-backup-1 valkey-node-backup-2'
    healthcheck: &healthcheck_backup
      test: [ "CMD-SHELL", "OUT=`valkey-cli cluster slots`; echo $$OUT | grep 172.16.1.20 || exit 1; echo $$OUT | grep 172.16.1.21 || exit 1; echo $$OUT | grep 172.16.1.22 || exit 1; echo $$OUT | grep 172.16.1.23 || exit 1; echo $$OUT | grep 172.16.1.24 || exit 1; echo $$OUT | grep 172.16.1.25 || exit 1;" ]
      interval: 1s
      timeout: 3s
      retries: 30

  valkey-node-backup-1:
    image: bitnamilegacy/valkey-cluster:7.2.5-debian-12-r4
    networks:
      cluster_subnet:
        ipv4_address: 172.16.1.21
    environment: *environment_backup
    healthcheck: *healthcheck_backup

  valkey-node-backup-2:
    image: bitnamilegacy/valkey-cluster:7.2.5-debian-12-r4
    networks:
      cluster_subnet:
        ipv4_address: 172.16.1.22
    environment: *environment_backup
    healthcheck: *healthcheck_backup

  valkey-node-backup-3:
    image: bitnamilegacy/valkey-cluster:7.2.5-debian-12-r4
    networks:
      cluster_subnet:
        ipv4_address: 172.16.1.23
    environment: *environment_backup
    healthcheck: *healthcheck_backup

  valkey-node-backup-4:
    image: bitnamilegacy/valkey-cluster:7.2.5-debian-12-r4
    networks:
      cluster_subnet:
        ipv4_address: 172.16.1.24
    environment: *environment_backup
    healthcheck: *healthcheck_backup

  valkey-node-backup-5:
    image: bitnamilegacy/valkey-cluster:7.2.5-debian-12-r4
    networks:
      cluster_subnet:
        ipv4_address: 172.16.1.25
    environment: *environment_backup
    healthcheck: *healthcheck_backup

  valkey-cluster-init-primary:
    image: bitnamilegacy/valkey-cluster:7.2.5-debian-12-r4
    networks:
      cluster_subnet:
        ipv4_address: 172.16.1.2
    depends_on:
      - valkey-node-primary-0
      - valkey-node-primary-1
      - valkey-node-primary-2
      - valkey-node-primary-3
      - valkey-node-primary-4
      - valkey-node-primary-5
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'VALKEY_CLUSTER_REPLICAS=1'
      - 'VALKEY_NODES=valkey-node-primary-0 valkey-node-primary-1 valkey-node-primary-2 valkey-node-primary-3 valkey-node-primary-4 valkey-node-primary-5'
      - 'VALKEY_CLUSTER_CREATOR=yes'

  valkey-cluster-init-backup:
    image: bitnamilegacy/valkey-cluster:7.2.5-debian-12-r4
    networks:
      cluster_subnet:
        ipv4_address: 172.16.1.3
    depends_on:
      - valkey-node-backup-0
      - valkey-node-backup-1
      - valkey-node-backup-2
      - valkey-node-backup-3
      - valkey-node-backup-4
      - valkey-node-backup-5
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'VALKEY_CLUSTER_REPLICAS=1'
      - 'VALKEY_NODES=valkey-node-backup-0 valkey-node-backup-1 valkey-node-backup-2 valkey-node-backup-3 valkey-node-backup-4 valkey-node-backup-5'
      - 'VALKEY_CLUSTER_CREATOR=yes'

  shotover-0:
    networks:
      cluster_subnet:
        ipv4_address: 172.16.1.4
    depends_on:
      valkey-node-primary-0:
        condition: service_healthy
      valkey-node-primary-1:
        condition: service_healthy
      valkey-node-primary-2:
        condition: service_healthy
      valkey-node-primary-3:
        condition: service_healthy
      valkey-node-primary-4:
        condition: service_healthy
      valkey-node-primary-5:
        condition: service_healthy
      valkey-node-backup-0:
        condition: service_healthy
      valkey-node-backup-1:
        condition: service_healthy
      valkey-node-backup-2:
        condition: service_healthy
      valkey-node-backup-3:
        condition: service_healthy
      valkey-node-backup-4:
        condition: service_healthy
      valkey-node-backup-5:
        condition: service_healthy
    image: shotover/shotover-proxy:v0.7.0
    volumes:
      - .:/config

networks:
  cluster_subnet:
    name: cluster_subnet
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/24
          gateway: 172.16.1.1
